#!/bin/bash
# build args extracts from IMAGE_TAG, that is provided at building trigger

prefix=$(echo $IMAGE_NAME | grep -oP "^.*?-")
suffix=$(echo $IMAGE_NAME | grep -oP "^.*?-\K.*$")

# replace right prefix for parent image
if [ "${prefix}" == "cuda-" ]
then
	prefix="nvidia/cuda:"
elif [ "${prefix}" == "ubuntu-" ]
then
	prefix="ubuntu:"
fi

parent=${prefix}${suffix}

# if the tag is unsupported - stay it as is
if [ "${parent}" == "" ]
then
	parent=${IMAGE_NAME}
fi

docker build --build-arg --build-arg parent=$parent -f $DOCKERFILE_PATH -t $IMAGE_NAME .
